## <u> Binary-star population synthesis with POSYDON </u>

### 0. Control and load librairies

In [2]:
# Control if the right python environment is selected (HAS TO BE IN THE POSYDON_ENV !!!)
import sys
print(sys.executable)

/home/users/a/aguetar1/.conda/envs/posydon_env/bin/python

In [3]:
import posydon
import numpy as np

modules = {
    "POSYDON": posydon.__version__,
    "Numpy": np.__version__,
}

for name, version in modules.items():
    print(name.ljust(10), ":", version)

POSYDON    : 2.1.1
Numpy      : 1.26.4

In [4]:
import os
import shutil
from posydon.config import PATH_TO_POSYDON

print("Path to Posydon : ", PATH_TO_POSYDON)

Path to Posydon :  /home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages

- Create a new population_params.ini file from the population_params_default.ini

In [5]:
path_to_params = os.path.join(PATH_TO_POSYDON, "posydon/popsyn/population_params_default.ini")
shutil.copyfile(path_to_params, './population_params.ini')

'./population_params.ini'

### 1. First overview of Posydon's functions

#### 1.1 Population runner

In [6]:
# This function runs the population synthesis with the parameters in the .ini file. Takes about 30 seconds in this
# case. 

from posydon.popsyn.synthetic_population import PopulationRunner
poprun = PopulationRunner('./population_params.ini', verbose=True)

In [7]:
print('Number of binary populations:',len(poprun.binary_populations))
print('Metallicity:', poprun.binary_populations[0].metallicity)
print('Number of binaries:', poprun.binary_populations[0].number_of_binaries)

Number of binary populations: 1
Metallicity: 1.0
Number of binaries: 10

In [8]:
poprun.evolve()

100%|██████████| 10/10 [00:26<00:00,  2.64s/it]

Merging 1 files...
Files merged!
Saved merged files to 1e+00_Zsun_population.h5...
Removing files in /home/users/a/aguetar1/Posydon_Data/Tutorial_Notebooks/1e+00_Zsun_batches...

In [33]:
from posydon.popsyn.synthetic_population import Population
pop = Population('../Generated_Tuto_Data/1e+00_Zsun_population.h5')

Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max

In [34]:
pop.mass_per_metallicity

,simulated_mass,simulated_mass_single,simulated_mass_binaries,number_of_systems
metallicity,,,,
1.0,28135.548554,0.0,28135.548554,1000

1. The index (metallicity) is the metallicity of your population in solar units.
2. <u>simulated mass</u>: The total ZAMS mass that has been evolved in the population.
3. <u>simulated_mass_single</u>: The total ZAMS mass from initially single stars.
4. <u>simulated_mass_binaries</u>: The total ZAMS mass from initially binary stars.
5. <u>number_of_systems</u> Shows the number of systems in the file.

In [11]:
# you can also access the total number of systems in the file with
print("The number of system is :", pop.number_of_systems)

The number of system is : 1000

#### 1.2 Access to history of Binaries

In [12]:
# Access to all the binaries
pop.history

,state,event,time,orbital_period,eccentricity,lg_mtransfer_rate,step_names,step_times,S1_state,S1_mass,...,S2_he_core_mass,S2_he_core_radius,S2_co_core_mass,S2_co_core_radius,S2_center_h1,S2_center_he4,S2_surface_h1,S2_surface_he4,S2_surf_avg_omega_div_omega_crit,S2_spin
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,0.000000e+00,2.770992,0.0,NaN,initial_cond,0.000000,H-rich_Core_H_burning,10.262765,...,NaN,NaN,NaN,NaN,0.715500,2.703000e-01,NaN,NaN,NaN,NaN
0,contact,oCE2,2.301529e+07,1.748804,0.0,-32.673698,step_HMS_HMS,0.228342,H-rich_Core_H_burning,9.658657,...,0.000000,0.0,0.000000,0.000000,0.706753,2.786637e-01,0.715496,0.270272,0.698066,5.023317
0,merged,oMerging2,2.301529e+07,1.748804,0.0,-32.673698,step_CE,0.000043,H-rich_Core_H_burning,9.658657,...,0.000000,0.0,0.000000,0.000000,0.706753,2.786637e-01,0.715496,0.270272,0.698066,5.023317
0,merged,CC2,3.541418e+07,NaN,NaN,NaN,step_merged,6.868071,massless_remnant,0.000000,...,3.881377,NaN,2.530842,0.058577,0.000000,2.022008e-13,0.688741,0.296985,0.002638,2.269946
0,merged,NaN,3.541418e+07,NaN,NaN,NaN,step_SN,0.000409,massless_remnant,0.000000,...,NaN,NaN,2.530842,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
0,merged,END,3.541418e+07,NaN,NaN,NaN,step_end,0.000034,massless_remnant,0.000000,...,NaN,NaN,2.530842,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,detached,ZAMS,0.000000e+00,2.258081,0.0,NaN,initial_cond,0.000000,H-rich_Core_H_burning,9.078746,...,NaN,NaN,NaN,NaN,0.715500,2.703000e-01,NaN,NaN,NaN,NaN
1,contact,oCE2,2.719198e+07,0.822037,0.0,-2.140360,step_HMS_HMS,0.065696,H-rich_Core_H_burning,6.497147,...,0.000000,0.0,0.000000,0.000000,0.650805,3.351147e-01,0.715390,0.270318,0.928720,15.072677
1,merged,oMerging2,2.719198e+07,0.822037,0.0,-2.140360,step_CE,0.000041,H-rich_Core_H_burning,6.497147,...,0.000000,0.0,0.000000,0.000000,0.650805,3.351147e-01,0.715390,0.270318,0.928720,15.072677
1,merged,CC2,4.264818e+07,NaN,NaN,NaN,step_merged,0.761609,massless_remnant,0.000000,...,3.567844,NaN,2.290289,0.055298,0.000000,1.080039e-13,0.688056,0.297668,0.003589,3.018881

In [13]:
# Get access to individual binaries 
pop.history[5]

,state,event,time,orbital_period,eccentricity,lg_mtransfer_rate,step_names,step_times,S1_state,S1_mass,...,S2_he_core_mass,S2_he_core_radius,S2_co_core_mass,S2_co_core_radius,S2_center_h1,S2_center_he4,S2_surface_h1,S2_surface_he4,S2_surf_avg_omega_div_omega_crit,S2_spin
binary_index,,,,,,,,,,,,,,,,,,,,,
5,detached,ZAMS,0.000000e+00,39.328694,0.0,NaN,initial_cond,0.000000,H-rich_Core_H_burning,14.243003,...,NaN,NaN,NaN,NaN,0.715500,2.703000e-01,NaN,NaN,NaN,NaN
5,detached,CC1,1.608656e+07,86.806339,0.0,-99.0,step_HMS_HMS,2.490058,stripped_He_Core_C_depleted,4.865064,...,0.000000,0.0,0.000000,0.000000,0.254293,7.318467e-01,0.714170,0.271562,0.626911,9.906172
5,disrupted,NaN,1.608656e+07,NaN,NaN,NaN,step_SN,0.000358,NS,1.686150,...,0.000000,0.0,0.000000,0.000000,0.254293,7.318467e-01,0.714170,0.271562,0.626911,9.906172
5,disrupted,CC2,2.076294e+07,NaN,NaN,NaN,step_disrupted,2.889863,NS,1.686150,...,4.897307,NaN,3.349819,0.068883,0.000000,3.080504e-13,0.690406,0.295326,0.001292,0.967878
5,disrupted,NaN,2.076294e+07,NaN,NaN,NaN,step_SN,0.000357,NS,1.686150,...,NaN,NaN,3.349819,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
5,disrupted,END,2.076294e+07,NaN,NaN,NaN,step_end,0.000039,NS,1.686150,...,NaN,NaN,3.349819,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [14]:
# History of the first and fifth binaries
pop.history[[0,4]]

,state,event,time,orbital_period,eccentricity,lg_mtransfer_rate,step_names,step_times,S1_state,S1_mass,...,S2_he_core_mass,S2_he_core_radius,S2_co_core_mass,S2_co_core_radius,S2_center_h1,S2_center_he4,S2_surface_h1,S2_surface_he4,S2_surf_avg_omega_div_omega_crit,S2_spin
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,0.000000e+00,2.770992,0.0,NaN,initial_cond,0.000000,H-rich_Core_H_burning,10.262765,...,NaN,NaN,NaN,NaN,0.715500,2.703000e-01,NaN,NaN,NaN,NaN
0,contact,oCE2,2.301529e+07,1.748804,0.0,-32.673698,step_HMS_HMS,0.228342,H-rich_Core_H_burning,9.658657,...,0.000000,0.0,0.000000,0.000000,0.706753,2.786637e-01,0.715496,0.270272,0.698066,5.023317
0,merged,oMerging2,2.301529e+07,1.748804,0.0,-32.673698,step_CE,0.000043,H-rich_Core_H_burning,9.658657,...,0.000000,0.0,0.000000,0.000000,0.706753,2.786637e-01,0.715496,0.270272,0.698066,5.023317
0,merged,CC2,3.541418e+07,NaN,NaN,NaN,step_merged,6.868071,massless_remnant,0.000000,...,3.881377,NaN,2.530842,0.058577,0.000000,2.022008e-13,0.688741,0.296985,0.002638,2.269946
0,merged,NaN,3.541418e+07,NaN,NaN,NaN,step_SN,0.000409,massless_remnant,0.000000,...,NaN,NaN,2.530842,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
0,merged,END,3.541418e+07,NaN,NaN,NaN,step_end,0.000034,massless_remnant,0.000000,...,NaN,NaN,2.530842,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
4,detached,ZAMS,0.000000e+00,9.074732,0.0,NaN,initial_cond,0.000000,H-rich_Core_H_burning,10.093238,...,NaN,NaN,NaN,NaN,0.715500,2.703000e-01,NaN,NaN,NaN,NaN
4,contact,oDoubleCE2,2.677168e+07,2.932544,0.0,-2.615613,step_HMS_HMS,0.068763,H-rich_Shell_H_burning,6.615690,...,0.000000,0.0,0.000000,0.000000,0.651244,3.346655e-01,0.715389,0.270303,0.932529,3.290123
4,merged,oMerging2,2.677168e+07,2.932544,0.0,-2.615613,step_CE,0.000039,H-rich_Shell_H_burning,6.615690,...,0.000000,0.0,0.000000,0.000000,0.651244,3.346655e-01,0.715389,0.270303,0.932529,3.290123
4,merged,CC2,4.790974e+07,NaN,NaN,NaN,step_merged,0.744333,massless_remnant,0.000000,...,4.090452,NaN,2.693958,0.060643,0.000000,2.063061e-13,0.689437,0.296290,0.002501,2.161786
4,merged,NaN,4.790974e+07,NaN,NaN,NaN,step_SN,0.000368,massless_remnant,0.000000,...,NaN,NaN,2.693958,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
4,merged,END,4.790974e+07,NaN,NaN,NaN,step_end,0.000031,massless_remnant,0.000000,...,NaN,NaN,2.693958,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [15]:
# Get acces to only one parameter of all binaries
pop.history['time'] #.head()

                      time
binary_index
0             0.000000e+00
0             2.301529e+07
0             2.301529e+07
0             3.541418e+07
0             3.541418e+07
...                    ...
999           1.677730e+07
999           1.677730e+07
999           2.010350e+07
999           2.010350e+07
999           2.010350e+07

[6107 rows x 1 columns]

In [16]:
# Check what columns are in the history 
pop.history.columns # Or this command : pop.columns['history']

['state',
 'event',
 'time',
 'orbital_period',
 'eccentricity',
 'lg_mtransfer_rate',
 'step_names',
 'step_times',
 'S1_state',
 'S1_mass',
 'S1_log_R',
 'S1_log_L',
 'S1_lg_mdot',
 'S1_he_core_mass',
 'S1_he_core_radius',
 'S1_co_core_mass',
 'S1_co_core_radius',
 'S1_center_h1',
 'S1_center_he4',
 'S1_surface_h1',
 'S1_surface_he4',
 'S1_surf_avg_omega_div_omega_crit',
 'S1_spin',
 'S2_state',
 'S2_mass',
 'S2_log_R',
 'S2_log_L',
 'S2_lg_mdot',
 'S2_he_core_mass',
 'S2_he_core_radius',
 'S2_co_core_mass',
 'S2_co_core_radius',
 'S2_center_h1',
 'S2_center_he4',
 'S2_surface_h1',
 'S2_surface_he4',
 'S2_surf_avg_omega_div_omega_crit',
 'S2_spin']

#### 1.3 Select function

Only identifiers available : **state** - **event** - **step_names** - **S1_state** - **S2_state** - **index == X** - **column names**

In [17]:
# Select binaries index 9 
pop.history.select(where='index == 9')

,state,event,time,orbital_period,eccentricity,lg_mtransfer_rate,step_names,step_times,S1_state,S1_mass,...,S2_he_core_mass,S2_he_core_radius,S2_co_core_mass,S2_co_core_radius,S2_center_h1,S2_center_he4,S2_surface_h1,S2_surface_he4,S2_surf_avg_omega_div_omega_crit,S2_spin
binary_index,,,,,,,,,,,,,,,,,,,,,
9,detached,ZAMS,0.000000e+00,8.125478,0.000000,NaN,initial_cond,0.000000,H-rich_Core_H_burning,68.293163,...,NaN,NaN,NaN,NaN,7.155000e-01,2.703000e-01,NaN,NaN,NaN,NaN
9,detached,CC1,4.071016e+06,26.254855,0.000000,-90.092243,step_HMS_HMS,2.135619,H-rich_Core_C_depleted,17.507083,...,4.280971,0.141498,0.000000,0.000000,9.465463e-02,8.826907e-01,0.582955,0.403776,0.179006,0.873454
9,detached,NaN,4.071016e+06,27.405812,0.172256,NaN,step_SN,0.000357,BH,17.150526,...,4.280971,0.141498,0.000000,0.000000,9.465463e-02,8.826907e-01,0.582955,0.403776,0.179006,0.873454
9,RLO2,oRLO2,4.182179e+06,26.492149,0.000000,NaN,step_detached,0.656357,BH,17.150526,...,25.051102,NaN,0.000000,0.000000,8.132454e-31,9.860986e-01,0.569434,0.416698,0.324778,0.551912
9,detached,CC2,4.732646e+06,42.774449,0.000000,-99.000000,step_CO_HMS_RLO,0.432004,BH,17.193775,...,15.014723,0.399891,13.647999,0.141523,0.000000e+00,1.003511e-12,0.000000,0.216122,0.000938,0.019931
9,detached,NaN,4.732646e+06,64.483764,0.282780,NaN,step_SN,0.000508,BH,17.193775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021182
9,detached,maxtime,1.380000e+10,64.469766,0.282731,NaN,step_dco,0.004996,BH,17.193775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021182
9,detached,END,1.380000e+10,64.469766,0.282731,NaN,step_end,0.000032,BH,17.193775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021182

In [18]:
# Select all RL02 states and only time and state columms
pop.history.select(columns=['time','state'])

                      time     state
binary_index
0             0.000000e+00  detached
0             2.301529e+07   contact
0             2.301529e+07    merged
0             3.541418e+07    merged
0             3.541418e+07    merged
...                    ...       ...
999           1.677730e+07   contact
999           1.677730e+07    merged
999           2.010350e+07    merged
999           2.010350e+07    merged
999           2.010350e+07    merged

[6107 rows x 2 columns]

In [19]:
# Selection of a range of binaries
pop.history.select(start = 10, stop = 16)

,state,event,time,orbital_period,eccentricity,lg_mtransfer_rate,step_names,step_times,S1_state,S1_mass,...,S2_he_core_mass,S2_he_core_radius,S2_co_core_mass,S2_co_core_radius,S2_center_h1,S2_center_he4,S2_surface_h1,S2_surface_he4,S2_surf_avg_omega_div_omega_crit,S2_spin
binary_index,,,,,,,,,,,,,,,,,,,,,
1,merged,NaN,4.264818e+07,NaN,NaN,NaN,step_SN,0.000402,massless_remnant,0.000000,...,NaN,NaN,2.290289,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,merged,END,4.264818e+07,NaN,NaN,NaN,step_end,0.000038,massless_remnant,0.000000,...,NaN,NaN,2.290289,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2,detached,ZAMS,0.000000e+00,761.834383,0.0,NaN,initial_cond,0.000000,H-rich_Core_H_burning,13.347447,...,NaN,NaN,NaN,NaN,0.715500,0.270300,NaN,NaN,NaN,NaN
2,RLO1,oCE1,1.664641e+07,645.618583,0.0,-0.979676,step_HMS_HMS,0.070168,H-rich_Shell_H_burning,12.121840,...,0.0,0.0,0.000000,0.0,0.656855,0.329073,0.715438,0.270312,0.926555,2.215553
2,merged,oMerging1,1.664641e+07,645.618583,0.0,-0.979676,step_CE,0.000089,H-rich_Shell_H_burning,12.121840,...,0.0,0.0,0.000000,0.0,0.656855,0.329073,0.715438,0.270312,0.926555,2.215553
2,merged,CC1,1.737231e+07,NaN,NaN,NaN,step_merged,0.949664,H-rich_Core_C_depleted,9.322318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Not all the binaries have the same length of history 
pop.history_lengths

       length
index
0           6
1           6
2           6
3           6
4           6
...       ...
995         6
996         6
997         6
998         6
999         6

[1000 rows x 1 columns]

#### 1.4 Population.oneline

The oneline DataFrame contains, as the name suggests, a single line per binary. It contains initial and final conditions and some additional variables, such as the SN_type.

In [21]:
pop.oneline[5]

,state_i,event_i,time_i,orbital_period_i,eccentricity_i,lg_mtransfer_rate_i,step_names_i,step_times_i,S1_state_i,S1_mass_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
5,detached,ZAMS,0.0,39.328694,0.0,NaN,initial_cond,0.0,H-rich_Core_H_burning,14.243003,...,NaN,NaN,NaN,Last stable RLOF during postMS,NaN,NaN,NaN,0,1,1.0

In [22]:
# Get oneline per binaries 0 and 4 (i.e. the first and the fifth binaries)
pop.oneline[[0,4]]

,state_i,event_i,time_i,orbital_period_i,eccentricity_i,lg_mtransfer_rate_i,step_names_i,step_times_i,S1_state_i,S1_mass_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,0.0,2.770992,0.0,NaN,initial_cond,0.0,H-rich_Core_H_burning,10.262765,...,NaN,NaN,NaN,Unstable contact phase,NaN,NaN,NaN,0,1,1.0
4,detached,ZAMS,0.0,9.074732,0.0,NaN,initial_cond,0.0,H-rich_Core_H_burning,10.093238,...,NaN,NaN,NaN,Unstable contact phase,NaN,NaN,NaN,0,1,1.0

In [23]:
pop.oneline.select(where='index == 9')

,state_i,event_i,time_i,orbital_period_i,eccentricity_i,lg_mtransfer_rate_i,step_names_i,step_times_i,S1_state_i,S1_mass_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
9,detached,ZAMS,0.0,8.125478,0.0,NaN,initial_cond,0.0,H-rich_Core_H_burning,68.293163,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,1,1.0

In [24]:
pop.oneline.select(where = 'index == [0,9]')

,state_i,event_i,time_i,orbital_period_i,eccentricity_i,lg_mtransfer_rate_i,step_names_i,step_times_i,S1_state_i,S1_mass_i,...,interp_class_CO_HMS_RLO,interp_class_CO_HeMS,interp_class_CO_HeMS_RLO,mt_history_HMS_HMS,mt_history_CO_HMS_RLO,mt_history_CO_HeMS,mt_history_CO_HeMS_RLO,FAILED,WARNING,metallicity
binary_index,,,,,,,,,,,,,,,,,,,,,
0,detached,ZAMS,0.0,2.770992,0.0,NaN,initial_cond,0.0,H-rich_Core_H_burning,10.262765,...,NaN,NaN,NaN,Unstable contact phase,NaN,NaN,NaN,0,1,1.0
9,detached,ZAMS,0.0,8.125478,0.0,NaN,initial_cond,0.0,H-rich_Core_H_burning,68.293163,...,stable_MT,NaN,NaN,no RLOF,Last stable RLOF during postMS,NaN,NaN,0,1,1.0

In [25]:
pop.oneline.columns

['state_i',
 'event_i',
 'time_i',
 'orbital_period_i',
 'eccentricity_i',
 'lg_mtransfer_rate_i',
 'step_names_i',
 'step_times_i',
 'S1_state_i',
 'S1_mass_i',
 'S1_log_R_i',
 'S1_log_L_i',
 'S1_lg_mdot_i',
 'S1_he_core_mass_i',
 'S1_he_core_radius_i',
 'S1_co_core_mass_i',
 'S1_co_core_radius_i',
 'S1_center_h1_i',
 'S1_center_he4_i',
 'S1_surface_h1_i',
 'S1_surface_he4_i',
 'S1_surf_avg_omega_div_omega_crit_i',
 'S1_spin_i',
 'S2_state_i',
 'S2_mass_i',
 'S2_log_R_i',
 'S2_log_L_i',
 'S2_lg_mdot_i',
 'S2_he_core_mass_i',
 'S2_he_core_radius_i',
 'S2_co_core_mass_i',
 'S2_co_core_radius_i',
 'S2_center_h1_i',
 'S2_center_he4_i',
 'S2_surface_h1_i',
 'S2_surface_he4_i',
 'S2_surf_avg_omega_div_omega_crit_i',
 'S2_spin_i',
 'state_f',
 'event_f',
 'time_f',
 'orbital_period_f',
 'eccentricity_f',
 'lg_mtransfer_rate_f',
 'step_names_f',
 'step_times_f',
 'S1_state_f',
 'S1_mass_f',
 'S1_log_R_f',
 'S1_log_L_f',
 'S1_lg_mdot_f',
 'S1_he_core_mass_f',
 'S1_he_core_radius_f',
 'S1_co_core_mass_f',
 'S1_co_core_radius_f',
 'S1_center_h1_f',
 'S1_center_he4_f',
 'S1_surface_h1_f',
 'S1_surface_he4_f',
 'S1_surf_avg_omega_div_omega_crit_f',
 'S1_spin_f',
 'S2_state_f',
 'S2_mass_f',
 'S2_log_R_f',
 'S2_log_L_f',
 'S2_lg_mdot_f',
 'S2_he_core_mass_f',
 'S2_he_core_radius_f',
 'S2_co_core_mass_f',
 'S2_co_core_radius_f',
 'S2_center_h1_f',
 'S2_center_he4_f',
 'S2_surface_h1_f',
 'S2_surface_he4_f',
 'S2_surf_avg_omega_div_omega_crit_f',
 'S2_spin_f',
 'S1_natal_kick_array_0',
 'S1_natal_kick_array_1',
 'S1_natal_kick_array_2',
 'S1_natal_kick_array_3',
 'S1_SN_type',
 'S1_f_fb',
 'S1_spin_orbit_tilt_first_SN',
 'S1_spin_orbit_tilt_second_SN',
 'S2_natal_kick_array_0',
 'S2_natal_kick_array_1',
 'S2_natal_kick_array_2',
 'S2_natal_kick_array_3',
 'S2_SN_type',
 'S2_f_fb',
 'S2_spin_orbit_tilt_first_SN',
 'S2_spin_orbit_tilt_second_SN',
 'interp_class_HMS_HMS',
 'interp_class_CO_HMS_RLO',
 'interp_class_CO_HeMS',
 'interp_class_CO_HeMS_RLO',
 'mt_history_HMS_HMS',
 'mt_history_CO_HMS_RLO',
 'mt_history_CO_HeMS',
 'mt_history_CO_HeMS_RLO',
 'FAILED',
 'WARNING',
 'metallicity']

#### 1.5 Population.formation_channels

Formation_channels give a summary overview of a binary's evolutionary pathway.

In [26]:
# This load the formation channels
pop.calculate_formation_channels(mt_history = True)

In [27]:
# Print what's been loaded
pop.formation_channels

                         channel_debug                            channel
0          ZAMS_oCE2_oMerging2_CC2_END        ZAMS_oCE2_oMerging2_CC2_END
1          ZAMS_oCE2_oMerging2_CC2_END        ZAMS_oCE2_oMerging2_CC2_END
2          ZAMS_oCE1_oMerging1_CC1_END        ZAMS_oCE1_oMerging1_CC1_END
3    ZAMS_oDoubleCE2_oMerging2_CC2_END  ZAMS_oDoubleCE2_oMerging2_CC2_END
4    ZAMS_oDoubleCE2_oMerging2_CC2_END  ZAMS_oDoubleCE2_oMerging2_CC2_END
..                                 ...                                ...
995             ZAMS_oRLO1_CC1_CC2_END             ZAMS_oRLO1_CC1_CC2_END
996        ZAMS_oCE1_oMerging1_CC1_END        ZAMS_oCE1_oMerging1_CC1_END
997        ZAMS_oCE1_oMerging1_CC1_END        ZAMS_oCE1_oMerging1_CC1_END
998             ZAMS_oRLO1_CC1_CC2_END             ZAMS_oRLO1_CC1_CC2_END
999        ZAMS_oCE1_oMerging1_CC1_END        ZAMS_oCE1_oMerging1_CC1_END

[1000 rows x 2 columns]

### 2. Select a sub-population

The Population.export_selection() function will export just the indices of the binaries you’re interested in into a new file. The simulated mass will remain the same since they are dependent on the population run.

In [28]:
indices = [0, 9]

# Creates a new file called "selected.h5" with only the indices selected
pop.export_selection(indices, '../Generated_Tuto_Data/selection.h5', overwrite=True)

Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max

In [29]:
selected = Population('..//Generated_Tuto_Data/selection.h5')
selected.mass_per_metallicity

Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max

,simulated_mass,simulated_mass_single,simulated_mass_binaries,number_of_systems
metallicity,,,,
1.0,28135.548554,0.0,28135.548554,2

In [30]:
print('Selected simulated mass : ', np.sum(selected.oneline[['S1_mass_i', 'S2_mass_i']].to_numpy()))

Selected simulated mass :  130.20205425220584

- To create multi-metallicity populations file, we can do :

In [31]:
pop.export_selection(indices, '../Generated_Tuto_Data/selected.h5', overwrite=True)

selected = Population('..//Generated_Tuto_Data/selected.h5')
selected.mass_per_metallicity

Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max
Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max

,simulated_mass,simulated_mass_single,simulated_mass_binaries,number_of_systems
metallicity,,,,
1.0,28135.548554,0.0,28135.548554,2

In [32]:
# This will add to the file and add the extra simulated mass
pop.export_selection(indices, '../Generated_Tuto_Data/selected.h5', append=True)
selected = Population('../Generated_Tuto_Data/selected.h5')
selected.mass_per_metallicity

Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max
Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max

,simulated_mass,simulated_mass_single,simulated_mass_binaries,number_of_systems
metallicity,,,,
1.0,56271.097109,0.0,56271.097109,4

-> In this last example, there is twice each systems (2 systems at first then double it).