### 6. Evolve individual binaries

It can be extremely useful to evolve a single binary from specific initial conditions or to start at a specific evolutionary state. This is useful for debugging binaries and checking if your custom steps or flow are working correctly.

In [2]:
import os
import shutil
import numpy as np

#### 1. Evolve a ZAMS binary

To evolve a binary from ZAMS, we will:

1. Load the standard simulation properties.
2. Load the steps.
3. Initialise the binary.
4. Evolve it.

In [2]:
from posydon.config import PATH_TO_POSYDON

path_to_params = os.path.join(PATH_TO_POSYDON, "posydon/popsyn/population_params_default.ini")
shutil.copyfile(path_to_params, './population_params_single.ini')

'./population_params_single.ini'

Here we add the metallicity to each binary system defined in the .ini file (with the function sim_kwargs['step_name'][1].update(metallicity)). It add  a new key 'metallicity' with value = 1
It will look like this : 

```python
    stop_value = None
     # float or None (only for stop_method='stop_at_condition')
    stop_interpolate = True
     # True, False
    verbose = False
     # True, False
    metallicity = 1
```

In [ ]:
# Load the function to load the simualtion properties from the ini file

from posydon.popsyn.io import simprop_kwargs_from_ini
from posydon.binary_evol.simulationproperties import SimulationProperties

# Load the simulation properties from the default ini file
sim_kwargs = simprop_kwargs_from_ini('./population_params_single.ini')

# Manually add the metallicity to each step that requires it
metallicity = {'metallicity': 1}

sim_kwargs['step_HMS_HMS'][1].update(metallicity)
sim_kwargs['step_CO_HeMS'][1].update(metallicity)
sim_kwargs['step_CO_HMS_RLO'][1].update(metallicity)
sim_kwargs['step_CO_HeMS_RLO'][1].update(metallicity)
sim_kwargs['step_detached'][1].update(metallicity)
sim_kwargs['step_disrupted'][1].update(metallicity)
sim_kwargs['step_merged'][1].update(metallicity)
sim_kwargs['step_initially_single'][1].update(metallicity)

sim_prop = SimulationProperties(**sim_kwargs)

# Load the steps and requires data
sim_prop.load_steps(verbose = True)

STEP NAME           STEP FUNCTION            KWARGS
flow (<function flow_chart at 0x14884add1c60>, {})
step_HMS_HMS (<class 'posydon.binary_evol.MESA.step_mesa.MS_MS_step'>, {'interpolation_path': None, 'interpolation_filename': None, 'interpolation_method': 'linear3c_kNN', 'save_initial_conditions': True, 'track_interpolation': False, 'stop_method': 'stop_at_max_time', 'stop_star': 'star_1', 'stop_var_name': None, 'stop_value': None, 'stop_interpolate': True, 'verbose': False, 'metallicity': 1})
step_CO_HeMS (<class 'posydon.binary_evol.MESA.step_mesa.CO_HeMS_step'>, {'interpolation_path': None, 'interpolation_filename': None, 'interpolation_method': 'linear3c_kNN', 'save_initial_conditions': True, 'track_interpolation': False, 'stop_method': 'stop_at_max_time', 'stop_star': 'star_1', 'stop_var_name': None, 'stop_value': None, 'stop_interpolate': True, 'verbose': False, 'metallicity': 1})
step_CO_HMS_RLO (<class 'posydon.binary_evol.MESA.step_mesa.CO_HMS_RLO_step'>, {'interpolation_path': None, 'interpolation_filename': None, 'interpolation_method': 'linear3c_kNN', 'save_initial_conditions': True, 'track_interpolation': False, 'stop_method': 'stop_at_max_time', 'stop_star': 'star_1', 'stop_var_name': None, 'stop_value': None, 'stop_interpolate': True, 'verbose': False, 'metallicity': 1})
step_CO_HeMS_RLO (<class 'posydon.binary_evol.MESA.step_mesa.CO_HeMS_RLO_step'>, {'interpolation_path': None, 'interpolation_filename': None, 'interpolation_method': 'linear3c_kNN', 'save_initial_conditions': True, 'track_interpolation': False, 'stop_method': 'stop_at_max_time', 'stop_star': 'star_1', 'stop_var_name': None, 'stop_value': None, 'stop_interpolate': True, 'verbose': False, 'metallicity': 1})
step_detached (<class 'posydon.binary_evol.DT.step_detached.detached_step'>, {'matching_method': 'minimize', 'do_wind_loss': True, 'do_tides': True, 'do_gravitational_radiation': True, 'do_magnetic_braking': True, 'do_stellar_evolution_and_spin_from_winds': True, 'RLO_orbit_at_orbit_with_same_am': False, 'record_matching': False, 'verbose': False, 'metallicity': 1})
step_disrupted (<class 'posydon.binary_evol.DT.step_disrupted.DisruptedStep'>, {'record_matching': False, 'verbose': False, 'metallicity': 1})
step_merged (<class 'posydon.binary_evol.DT.step_merged.MergedStep'>, {'metallicity': 1})
step_initially_single (<class 'posydon.binary_evol.DT.step_initially_single.InitiallySingleStep'>, {'record_matching': False, 'verbose': False, 'metallicity': 1})
step_dco (<class 'posydon.binary_evol.DT.double_CO.DoubleCO'>, {'n_o_steps_interval': None})
step_SN (<class 'posydon.binary_evol.SN.step_SN.StepSN'>, {'mechanism': 'Fryer+12-delayed', 'engine': '', 'PISN': 'Hendriks+23', 'PISN_CO_shift': 0.0, 'PPI_extra_mass_loss': -20.0, 'ECSN': 'Tauris+15', 'conserve_hydrogen_envelope': False, 'conserve_hydrogen_PPI': False, 'max_neutrino_mass_loss': 0.5, 'max_NS_mass': 2.5, 'use_interp_values': True, 'use_profiles': True, 'use_core_masses': True, 'allow_spin_None': False, 'approx_at_he_depletion': False, 'kick': True, 'kick_normalisation': 'one_over_mass', 'sigma_kick_CCSN_NS': 265.0, 'sigma_kick_CCSN_BH': 265.0, 'sigma_kick_ECSN': 20.0, 'verbose': False})
step_CE (<class 'posydon.binary_evol.CE.step_CEE.StepCEE'>, {'prescription': 'alpha-lambda', 'common_envelope_efficiency': 1.0, 'common_envelope_option_for_lambda': 'lambda_from_grid_final_values', 'common_envelope_lambda_default': 0.5, 'common_envelope_option_for_HG_star': 'optimistic', 'common_envelope_alpha_thermal': 1.0, 'core_definition_H_fraction': 0.3, 'core_definition_He_fraction': 0.1, 'CEE_tolerance_err': 0.001, 'common_envelope_option_after_succ_CEE': 'two_phases_stableMT', 'verbose': False})
step_end (<class 'posydon.binary_evol.step_end.step_end'>, {})

In [3]:
# Load the binary and single star class 

from posydon.binary_evol.singlestar import SingleStar
from posydon.binary_evol.binarystar import BinaryStar

In [4]:
STAR1 = SingleStar(**{'mass' : 30.782576,'state': 'H-rich_Core_H_burning'})
STAR2 = SingleStar(**{'mass' : 20.273864,'state': 'H-rich_Core_H_burning'})

BINARY = BinaryStar(STAR1, STAR2, **{'time' : 0.0, 'state' : 'detached', 'event' : 'ZAMS',
 'orbital_period' : 3513.150157, 'eccentricity' : 0.0}, properties = sim_prop)

In [5]:
# NOTE : Depending on the evolution of the binary, you might get some warnings about the Roche Lobe calculation.
BINARY.evolve()

/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/utils/common_functions.py:268: EvolutionWarning: 'Trying to compute RL radius for nonexistent object'
/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/utils/common_functions.py:283: EvolutionWarning: 'Trying to compute RL radius for nonexistent companion'
/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/utils/common_functions.py:118: ReplaceValueWarning: 'A surf_avg_omega value is negative. Setting to zero.'
/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/utils/common_functions.py:246: EvolutionWarning: 'Trying to compute RL radius for binary with invalid separation'
/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/utils/common_functions.py:263: EvolutionWarning: 'Trying to compute RL radius for nonexistent object'
/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/utils/common_functions.py:278: EvolutionWarning: 'Trying to compute RL radius for nonexistent companion'
/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/binary_evol/SN/step_SN.py:522: InterpolationWarning: 'SN_MODEL_v2_01: The collapsed star was not interpolated! If use_profiles or use_core_masses is set to True, continue with the collapse.'

You’re now able to access the binary and evolutionary information. Using the function, <b style ='color:orange;'>BinaryStar.to_df()</b> we can inspect the evolution of the system.

In [7]:
# We will add the step names to the dataframe

col = ['time', 'step_names','event', 'orbital_period', 'eccentricity', 'S1_state', 'S2_state','S1_mass', 'S2_mass']

BINARY.to_df(extra_columns = {'step_names': 'string'})[col]

                      time      step_names  ...    S1_mass    S2_mass
binary_index                                ...
NaN           0.000000e+00    initial_cond  ...  30.782576  20.273864
NaN           6.735757e+06    step_HMS_HMS  ...  13.647261  19.854313
NaN           6.735757e+06         step_SN  ...  13.043450  19.854313
NaN           1.016206e+07  step_disrupted  ...  13.043450   9.851849
NaN           1.016206e+07         step_SN  ...  13.043450   5.310433
NaN           1.016206e+07        step_end  ...  13.043450   5.310433

[6 rows x 9 columns]

##### 1.1 Re-evolving a binary

In [8]:
# restore the original state 

BINARY.restore()
BINARY.to_df()

                 state event  ...  S2_total_mass_h1  S2_total_mass_he4
binary_index                  ...
NaN           detached  ZAMS  ...               NaN                NaN

[1 rows x 132 columns]

In [9]:
BINARY.evolve()

Even though we reset the binary, the natal kick properties stored in the natal kick array are not reset. This is because we want to be able to re-evolve the binary to the same final state. If you want to reset the natal kick array values, then set its elements to <b style = 'color:red;'>None</b>.

In [11]:
# Kick mangitude km/s, azimuthal angle rad, polar angle rad and mean anomaly rad (TODO check documentation)

print('Natal kick of binary star 1 :', BINARY.star_1.natal_kick_array)
print('Natal kick of binary star 2 :',BINARY.star_2.natal_kick_array)

Natal kick of binary star 1 : [66.16708264977689, 2.108288696663849, 1.3571937596067565, 1.2859895948467197]
Natal kick of binary star 2 : [233.99228314724064, 4.634353296377042, 1.9901871388366619, 1.4592736848742986]

In [12]:
# This will be exactly the same evolution as the previous one 

BINARY.to_df(extra_columns={'step_names':'string'})[col]

                      time      step_names  ...    S1_mass    S2_mass
binary_index                                ...
NaN           0.000000e+00    initial_cond  ...  30.782576  20.273864
NaN           6.735757e+06    step_HMS_HMS  ...  13.647261  19.854313
NaN           6.735757e+06         step_SN  ...  13.043450  19.854313
NaN           1.016206e+07  step_disrupted  ...  13.043450   9.851849
NaN           1.016206e+07         step_SN  ...  13.043450   5.310433
NaN           1.016206e+07        step_end  ...  13.043450   5.310433

[6 rows x 9 columns]

##### 1.2 Changing the kick

In [13]:
BINARY.restore()
BINARY.to_df()

                 state event  ...  S2_total_mass_h1  S2_total_mass_he4
binary_index                  ...
NaN           detached  ZAMS  ...               NaN                NaN

[1 rows x 132 columns]

In [14]:
# [velocity, azimuthal angle, polar angle, phase]

BINARY.star_1.natal_kick_array = [1000, 0.858129274334538, 1.9157148786534735, 1.8675467897282945]
BINARY.star_2.natal_kick_array = [None, None, None, None] # Default

print('Natal kick of binary star 1 :', BINARY.star_1.natal_kick_array)
print('Natal kick of binary star 2 :', BINARY.star_2.natal_kick_array)

Natal kick of binary star 1 : [1000, 0.858129274334538, 1.9157148786534735, 1.8675467897282945]
Natal kick of binary star 2 : [None, None, None, None]

In [16]:
BINARY.evolve()
BINARY.to_df(extra_columns={'step_names':'string'})[col]

                      time      step_names  ...    S1_mass    S2_mass
binary_index                                ...
NaN           0.000000e+00    initial_cond  ...  30.782576  20.273864
NaN           6.735757e+06    step_HMS_HMS  ...  13.647261  19.854313
NaN           6.735757e+06         step_SN  ...  13.043450  19.854313
NaN           1.016206e+07  step_disrupted  ...  13.043450   9.851849
NaN           1.016206e+07         step_SN  ...  13.043450   5.310433
NaN           1.016206e+07        step_end  ...  13.043450   5.310433

[6 rows x 9 columns]

##### 1.3 Evolve from a specific step

In [ ]:
BINARY.restore(3) # Restore to step 3
BINARY.to_df()

#### 2. Loading a binary from an existing population

For this one, we will use <b style='color:orange;'> BBH_contact.h5 </b> file and <b style='color:red;'>ITS</b> corresponding file, i.e. <b style='color:orange;'>population_params2.ini</b>.

In [18]:
from posydon.popsyn.synthetic_population import Population

pop = Population('BBH_contact.h5')

Missing ini parameter: orbital_separation_scheme
Missing ini parameter: orbital_separation_min
Missing ini parameter: orbital_separation_max

In [20]:
# Because the original population contains two extra columns, these have to be defined manually here.
# Otherwise, resetting the binaries will fail. 

BINARY = BinaryStar.from_df(pop.history[0], extra_columns = {'step_names':'string', 'step_times':'float'})

# You have to set the simulation properties for the binary 
BINARY.propertires = sim_prop

# Set the natal kick arrays from the onelne to get the exat same evolution as the original binary
BINARY.star_1.natal_kick_array = pop.oneline[0][['S1_natal_kick_array_0', 'S1_natal_kick_array_1', 
                                                 'S1_natal_kick_array_2', 'S1_natal_kick_array_3']].values.flatten()
BINARY.star_2.natal_kick_array = pop.oneline[0][['S2_natal_kick_array_0', 'S2_natal_kick_array_1', 
                                                 'S2_natal_kick_array_2', 'S2_natal_kick_array_3']].values.flatten()

In [21]:
BINARY.to_df(extra_columns={'step_names':'string'})[col]

                      time       step_names  ...    S1_mass    S2_mass
binary_index                                 ...
0             0.000000e+00     initial_cond  ...  39.680646  28.818876
0             5.884773e+06     step_HMS_HMS  ...  17.887336  33.766741
0             5.884773e+06          step_SN  ...  17.448928  33.766741
0             6.377155e+06    step_detached  ...  17.448928  34.848539
0             7.785821e+06  step_CO_HMS_RLO  ...  18.029109  16.336831
0             7.785821e+06          step_SN  ...  18.029109  16.033050
0             1.061960e+10         step_dco  ...  18.029109  16.033050
0             1.061960e+10         step_end  ...  18.029109  16.033050

[8 rows x 9 columns]

In [22]:
BINARY.restore()

In [24]:
BINARY.evolve()
BINARY.to_df(extra_columns={'step_names':'string'})[col]

AttributeError: 'tuple' object has no attribute 'get'

#### 3. Evolving a Binary star starting from an arbitrary state

If you want to evolve a custom binary star, you can do so by manually creating the <I style='color:red;'>BinaryStar</I> object and providing the <I style='color:red;'>SimulationProperties</I> object. 

Here is an example of a neutron star with a low-mass helium companion in Roche Lobe overflow.

In [25]:
# We initialise the binary to be tight and Roche lobe overflowing in a circular orbit.
binary = BinaryStar(star_1 = SingleStar(**{'state' : 'NS',
                                           'mass' : 1.1,
                                           'spin' : 0.,}),
                    star_2 = SingleStar(**{'state' : 'H-rich_Core_H_burning',
                                           'mass' : 2.5,
                                           'natal_kick_array' : [10., 0., 0., 0.]}),
                    **{'time' : 0.,
                       'state' : 'RLO2',
                       'event' : 'oRLO2',
                       'orbital_period' : 1.,
                       'eccentricity' : 0.},
                    properties = sim_prop,
                    )
binary.evolve()
binary.to_df(extra_columns={'step_names':'string'})[col]

                      time       step_names  ...   S1_mass   S2_mass
binary_index                                 ...
NaN           0.000000e+00     initial_cond  ...  1.100000  2.500000
NaN           2.352552e+08  step_CO_HMS_RLO  ...  1.893069  0.164589
NaN           2.352552e+08          step_CE  ...  1.893069  0.164589
NaN           2.352552e+08      step_merged  ...  1.893069  0.000000
NaN           2.352552e+08         step_end  ...  1.893069  0.000000

[5 rows x 9 columns]

In [26]:
# We perform the same evolution, but with a stripped helium star to go to the CO_HeMS_RLO grid
binary = BinaryStar(star_1 = SingleStar(**{'state' : 'NS',
                                           'mass' : 1.1,
                                           'spin' : 0.,}),
                    star_2 = SingleStar(**{'state' : 'stripped_He_Core_He_burning',
                                           'mass' : 2.5,
                                           'natal_kick_array' : [10., 0., 0., 0.]}),
                    **{'time' : 0.,
                       'state' : 'RLO2',
                       'event' : 'oRLO2',
                       'orbital_period' : 1.,
                       'eccentricity' : 0.},
                    properties = sim_prop,
                    )
binary.evolve()
binary.to_df(extra_columns={'step_names':'string'})[col]

/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/interpolation/IF_interpolation.py:1173: InterpolationWarning: '1NN interpolation used for 1 binaries out of hull. Parameter-wise distance (Unnormalized) for point with maximum out-of-hull euclidian distance (Normalized): [0.08012213 2.38677534 2.23387895]'

                      time        step_names  ...   S1_mass   S2_mass
binary_index                                  ...
NaN           0.000000e+00      initial_cond  ...  1.100000  2.500000
NaN           2.271486e+04  step_CO_HeMS_RLO  ...  1.100794  1.748416
NaN           2.271486e+04           step_SN  ...  1.100794  1.277584
NaN           1.380000e+10          step_dco  ...  1.100794  1.277584
NaN           1.380000e+10          step_end  ...  1.100794  1.277584

[5 rows x 9 columns]

We will change the binary to a much wider system and have it start in the detached state. This requires additional starting information to allow the star to be matched to the single star grids.

In [27]:
from posydon.utils.constants import Zsun
from posydon.utils.common_functions import orbital_separation_from_period

import numpy as np
Z = 1.0

# Setup the central abundances
zams_table = {2.: 2.915e-01,
                      1.: 2.703e-01,
                      0.45: 2.586e-01,
                      0.2: 2.533e-01,
                      0.1: 2.511e-01,
                      0.01: 2.492e-01,
                      0.001: 2.49e-01,
                      0.0001: 2.49e-01}

Y = zams_table[Z]
Z = Z*Zsun
X = 1 - Y - Z

In [28]:
STAR1 = SingleStar(**{'mass':1.2,
                      'state': 'NS'})

STAR2 = SingleStar(**{'mass': 17.782576,
                      'state': 'H-rich_Core_H_burning',
                      # add the metallicity and central abundances
                      'metallicity':Z,
                      'center_h1':X,
                      'center_he4':Y,
                      # add a numerical value for the radius
                      'log_R': np.nan,
                      # add the helium core mass
                      'he_core_mass': 0.0,
                      })

binary = BinaryStar(STAR1, STAR2,
                    **{'time' : 0.,
                       'state' : 'detached',
                       'event' : None,
                       'orbital_period' : 5000.,
                        # calculate the separation; current bug that the separation is not automatically calculated if orbital period is given
                       'separation': orbital_separation_from_period(5000., 17.782576, 1.2),
                       'eccentricity' : 0.},
                    properties = sim_prop,
                    )
binary.evolve()
binary.to_df(extra_columns={'step_names':'string'})[col]

/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/interpolation/IF_interpolation.py:1475: InterpolationWarning: 'normalization was skipped during interpolation: c=initial_MT, inds=[0]'
/home/users/a/aguetar1/.conda/envs/posydon_env/lib/python3.11/site-packages/posydon/interpolation/IF_interpolation.py:1499: InterpolationWarning: 'de-normalization was skipped during interpolation: c=initial_MT, inds=[0]'

                      time       step_names  ...  S1_mass    S2_mass
binary_index                                 ...
NaN           0.000000e+00     initial_cond  ...  1.20000  17.782576
NaN           1.116364e+07    step_detached  ...  1.20000  15.839361
NaN           1.116458e+07  step_CO_HMS_RLO  ...  1.20001  15.533734
NaN           1.116458e+07          step_CE  ...  1.20001   6.405666
NaN                    NaN     step_CO_HeMS  ...      NaN        NaN
NaN                    NaN         step_end  ...      NaN        NaN

[6 rows x 9 columns]